# This workflow will build the source code and create a new github package.
# For more information see: https://github.com/marketplace/actions/build-and-push-docker-images

name: Build

on:
  push:
    branches:
      - GHAS*
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - GHAS*
      - develop
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://git.io/codeql-language-support

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
    - name: Build with Maven
      run: mvn clean compile

